### ISSUE TITLE
Installation of cpacs2to3 via anaconda fails with UnsatisfiableError

### ISSUE THREAD

**Issue by RlanderRISCSW** [DLR-SC/cpacs2to3#13]
When trying to install cpacs2to3 via `conda create -n cpacs2to3 python=3.5 cpacs2to3 -c dlr-sc` on Windows the operation fails with following error message:

> UnsatisfiableError: The following specifications were found to be in conflict:
>  - cpacs2to3

Also setting up the devel environment via `conda create -n cpacs2to3_devel python=3.5 tigl3 tigl tixi3 tixi -c dlr-sc` fails with following error message:
> UnsatisfiableError: The following specifications were found to be in conflict:
>  - tigl -> pythonocc-core==0.17
>  - tigl3 -> pythonocc-core==0.17.3

**Comment by rainman110** [comment]
Good to know... I'll update TiGL 2 to use pythonocc 0.17.3

**Comment by rainman110** [comment]
@RlanderRISCSW Can you please retry?

**Comment by RlanderRISCSW** [comment]
thank you very much, works now
