### ISSUE TITLE
Package stale? How to install?

### ISSUE THREAD

**Issue by MarkusZimmerDLR** [DLR-SC/cpacs2to3#25]
Dear tigl-folks,

the instructions in the readme specify python 3.5.
Currently, there are no more python 3.5 packages for tigl and tigl3 provided.

I tried installing it with the python 3.7 distributions. However, this fails since the OCC package seams to be too new and breaks the code. (e.g. `OCC.core` does not exist)
(Also, the setup.py syntax seem to have some keywords wrong or for older standards. E.g. `requires` and `install_requires`. Since `numpy` is not installed when installing this package manually.)

Has the converter been moved to another repo?

Cheers
Markus

**Comment by joergbrech** [comment]
> Has the converter been moved to another repo?

No, we just haven't properly updated this code in a while, because of missing demand. The two points you are mentioning should be fairly easy to fix. 

What might be tricky (we would have to try and see) is that this tool has tigl (<3) and tigl3 (>=3.0.0) as a dependency: Firstly, we haven't built conda packages for tigl in a while, so there may be none available for Python 3.7 and greater (this is an easy fix as well). Secondly, we might run into a dependency conflict, because tigl requires a much older version of OpenCascade than tigl3....

-----

Edit: I only found this reference to OCC:

https://github.com/DLR-SC/cpacs2to3/blob/7576b89c859d24b74c10fef779ee5a2bc8b94da2/cpacs2to3/convert_coordinates.py#L6

and I believe it should work with newer OCCT Versions, but not older ones. Which version did you try?

**Comment by MarkusZimmerDLR** [comment]
I changed the OCC import and installed the requirements myself.
However, the code now fails when a tigl-handle is generated.

```
INFO: Loading CPACS-2 file 'toolOutput.xml' with TiGL 2
WRN 11/08 10:27:01 tigl.cpp:193] CPACS dataset version is higher than TIGL library version!
Error: Element chosen by XPath "/cpacs/vehicles/aircraft|/cpacs/vehicles/rotorcraft" expression is not unique. 
ERR 11/08 10:27:01 tigl.cpp:130] [TiXI] Error: Element chosen by XPath "/cpacs/vehicles/aircraft|/cpacs/vehicles/rotorcraft" expression is not unique. 
ERR 11/08 10:27:01 tigl.cpp:206] No configuration specified!
Traceback (most recent call last):
  File "/work/zimm_ms/private_conda_envs/cpacs2to3/bin/cpacs2to3", line 33, in <module>
    sys.exit(load_entry_point('cpacs2to3', 'console_scripts', 'cpacs2to3')())
  File "/home/ae/zimm_ms/workspace2/cps2to3/cpacs2to3/cpacs2to3/cpacs_converter.py", line 679, in main
    vu.update(cpacs_file, args, version_new)
  File "/home/ae/zimm_ms/workspace2/cps2to3/cpacs2to3/cpacs2to3/cpacs_converter.py", line 653, in update
    updater.update(cpacs, args)
  File "/home/ae/zimm_ms/workspace2/cps2to3/cpacs2to3/cpacs2to3/cpacs_converter.py", line 542, in upgrade_2_to_3
    convert_geometry(filename, cpacs_handle, old_cpacs_file)
  File "/home/ae/zimm_ms/workspace2/cps2to3/cpacs2to3/cpacs2to3/convert_coordinates.py", line 358, in convert_geometry
    tigl2.open(old_cpacs_file, "")
  File "/work/zimm_ms/private_conda_envs/cpacs2to3/lib/python3.7/site-packages/tigl/tiglwrapper.py", line 244, in open
    self.openCPACSConfiguration(tixi._handle.value, uid)
  File "/work/zimm_ms/private_conda_envs/cpacs2to3/lib/python3.7/site-packages/tigl/tiglwrapper.py", line 260, in openCPACSConfiguration
    catch_error(errorCode, 'tiglOpenCPACSConfiguration', tixiHandle, configurationUID)
  File "/work/zimm_ms/private_conda_envs/cpacs2to3/lib/python3.7/site-packages/tigl/tiglwrapper.py", line 190, in catch_error
    raise TiglException(returncode, args, kwargs)
tigl.tiglwrapper.TiglException: TIGL_ERROR (1) [('tiglOpenCPACSConfiguration', 1, ''), {}] {}
```

**Comment by MarkusZimmerDLR** [comment]
> and I believe it should work with newer OCCT Versions, but not older ones. Which version did you try?

The version installed along tigl and tigl3 is

`pythonocc-core            0.17.3          py37h2bc3f7f_12    dlr-sc`

**Comment by joergbrech** [comment]
> I changed the OCC import and installed the requirements myself. However, the code now fails when a tigl-handle is generated.
> 

My guess is that you have more than one rotorcraft in your CPACS file and the offending line is here: 

https://github.com/DLR-SC/cpacs2to3/blob/7576b89c859d24b74c10fef779ee5a2bc8b94da2/cpacs2to3/convert_coordinates.py#L358

So cpacs2to3 assumes that only one configuration is present, see also [the tigl doc](https://dlr-sc.github.io/tigl/doc/2.2.3/group__GeneralFunctions.html#gae26118f1a8364498d26ca9bf318fccb8). It would be better to run the code in `convert_geometry` for all configurations.

**Comment by joergbrech** [comment]
> > and I believe it should work with newer OCCT Versions, but not older ones. Which version did you try?
> 
> The version installed along tigl and tigl3 is
> 
> `pythonocc-core 0.17.3 py37h2bc3f7f_12 dlr-sc`

Ok, so the cpacs2to3 should wrap the import in an OCCT Version check and use either `OCC.Core.TopoDS` or `OCC.TopoDS` depending on the pythonocc version.

**Comment by MarkusZimmerDLR** [comment]
For my test, I added a new kwarg `configuration` to explicitly set the configuration to be converted. Looping over all available configurations is also an option.

Let's see if something else comes up first.

**Comment by MarkusZimmerDLR** [comment]
This ran through and tiglviewer3 is able to display the structure. 

For my case, I only want to convert the main configuration. The other configuration is an engine-description, which I want to keep as is.

Thus, I will keep the explicit configuration switch and add the option to convert all.
I'll change the OCC import to a try except block.

I'll pipe it back with a PR and you can have a look.

**Comment by joergbrech** [comment]
> I'll pipe it back with a PR and you can have a look.

Perfect. Thanks!

**Comment by MarkusZimmerDLR** [comment]
#26
