### ISSUE TITLE
Guide Curve Conversion

### ISSUE THREAD

**Issue by rainman110** [DLR-SC/cpacs2to3#3]
The definition of guide curves has changed. We should convert it!

**Comment by joergbrech** [comment]
This issue depends on https://github.com/DLR-SC/tigl/issues/436

**Comment by joergbrech** [comment]
Guide Curve Conversion seems to work now. However, we need to update TiGL2 and TiGL3 in the conda repo:

 - TiGL 2: See DLR-SC/tigl#436
 - TiGL 3: This issue requires the changes from DLR-SC/tigl@e0fe23117be12f081be7a4aa9458f0e3456c37b2 which are not in the latest release (the code uses `getLength(...)` from `tiglcommonfunctions.h`)

**Comment by rainman110** [comment]
I suggest, we make a proper tigl 2 release and update the conda package. For tigl 3 we just make a snapshot.
